"""Sample packing: the samples.yaml schema, pitch checks and samples.js."""

from __future__ import annotations

import json
import math
import shutil
import wave
from pathlib import Path

import pytest
from pydantic import ValidationError

from samples import (
    Packed,
    SampleError,
    fetch,
    measure_pitch,
    note_name,
    prepare,
    problems,
    write_js,
)
from schema.samples import Instrument, SampleSet
from worlds import load_model

needs_ffmpeg = pytest.mark.skipif(
    shutil.which("ffmpeg") is None, reason="ffmpeg not installed"
)


def _inst(**extra: object) -> dict:
    data = {"id": "pizz", "library": "vsco2ce", "files": ["a.wav"]}
    data.update(extra)
    return data


class TestSchema:
    def test_valid(self) -> None:
        SampleSet.model_validate({"licence": "CC0", "instruments": [_inst()]})

    def test_duplicate_instrument_ids(self) -> None:
        data = {"licence": "CC0", "instruments": [_inst(), _inst()]}
        with pytest.raises(ValidationError, match="duplicate instrument ids"):
            SampleSet.model_validate(data)

    def test_file_listed_twice(self) -> None:
        with pytest.raises(ValidationError, match="listed twice"):
            Instrument.model_validate(_inst(files=["a.wav", "a.wav"]))

    def test_needs_a_file(self) -> None:
        with pytest.raises(ValidationError):
            Instrument.model_validate(_inst(files=[]))

    def test_yard_samples_file_is_valid(self) -> None:
        path = (
            Path(__file__).resolve().parents[1]
            / "worlds/reksio/games/yard/samples.yaml"
        )
        assert load_model(path, SampleSet).instruments


class TestHelpers:
    def test_note_name(self) -> None:
        assert note_name(69) == "A4"
        assert note_name(70.4) == "A#4"
        assert note_name(34) == "A#1"

    def test_problems_flags_out_of_tune(self) -> None:
        ok = Packed("pizz", "a.wav", 69.2, 20.0, b"")
        off = Packed("pizz", "b.wav", 69.7, -30.0 + 100, b"")
        oneshot = Packed("timpani", "c.wav", None, None, b"")
        assert problems([ok, oneshot]) == []
        assert len(problems([off])) == 1

    def test_unknown_library(self, tmp_path: Path) -> None:
        with pytest.raises(SampleError, match="unknown library"):
            fetch("nope", "a.wav", tmp_path)

    def test_cached_file_is_not_downloaded(self, tmp_path: Path) -> None:
        cached = tmp_path / "vcsl" / "x" / "a.wav"
        cached.parent.mkdir(parents=True)
        cached.write_bytes(b"cached")
        assert fetch("vcsl", "x/a.wav", tmp_path) == cached

    def test_write_js(self, tmp_path: Path) -> None:
        packed = [
            Packed("pizz", "b.wav", 72.0, 0.0, b"\x01\x02"),
            Packed("pizz", "a.wav", 69.0, 0.0, b"\x03"),
            Packed("timpani", "c.wav", None, None, b"\x04"),
        ]
        out = write_js(packed, "CC0.", tmp_path / "samples.js")
        text = out.read_text(encoding="utf-8")
        assert text.startswith("// Generated by `main.py samples`")
        table = json.loads(text.split("const SAMPLES = ", 1)[1])
        assert [e["midi"] for e in table["pizz"]] == [69.0, 72.0]  # sorted by pitch
        assert "midi" not in table["timpani"][0]
        assert table["pizz"][0]["data"] == "Aw=="


@needs_ffmpeg
class TestPrepareAndMeasure:
    def test_measures_a_known_tone(self, tmp_path: Path) -> None:
        sr = 22_050
        src = tmp_path / "tone.wav"
        with wave.open(str(src), "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(sr)
            frames = bytearray()
            for i in range(sr * 2):  # 2 s of A4 (440 Hz), after 0.3 s of silence
                v = (
                    0
                    if i < sr * 0.3
                    else int(12000 * math.sin(2 * math.pi * 440 * i / sr))
                )
                frames += v.to_bytes(2, "little", signed=True)
            w.writeframes(bytes(frames))
        inst = Instrument.model_validate(_inst(max_seconds=1.0))
        wav, mp3 = prepare(src, inst, tmp_path)
        assert mp3.stat().st_size > 0
        with wave.open(str(wav)) as w:
            assert w.getnframes() / w.getframerate() <= 1.01  # trimmed and cut
        assert measure_pitch(wav) == pytest.approx(69, abs=0.3)
