"""Reksio's bark for the games, cut from the original barks Adam marked.

The bark clip holds two quick barks. They are cut apart, cleaned up and packed
into a script the game loads (browsers won't hand ``file://`` audio to Web
Audio, but they do run local scripts). The game then plays them a little higher
and quicker by a random amount each time, so they are close to the original
but never quite it, and never the same twice.

The packed script is the original recording, so it is written under the
world's gitignored ``audio/`` folder and stays local. A game without it uses
its own synthesised bark.
"""

from __future__ import annotations

import base64
import io
import json
from pathlib import Path

import numpy as np

from config import BARK_FADE_S, BARK_MIN_S, BARK_PAD_S, BARK_PEAK, BARK_THRESHOLD


class BarkError(Exception):
    """The bark clip is missing or holds no bark."""


def split(y: np.ndarray, sr: int, hop: int = 256) -> list[tuple[int, int]]:
    """Sample ranges of each bark: stretches louder than BARK_THRESHOLD of the
    loudest moment, at least BARK_MIN_S long, padded by BARK_PAD_S."""
    if not len(y) or not np.any(y):
        return []
    frames = max(1, len(y) // hop)
    rms = np.array(
        [np.sqrt(np.mean(y[i * hop : (i + 1) * hop] ** 2)) for i in range(frames)]
    )
    loud = rms > rms.max() * BARK_THRESHOLD
    pad = int(BARK_PAD_S * sr)
    segments = []
    start = None
    for i, on in enumerate([*loud, False]):
        if on and start is None:
            start = i
        elif not on and start is not None:
            a, b = start * hop, i * hop
            if (b - a) / sr >= BARK_MIN_S:
                segments.append((max(0, a - pad), min(len(y), b + pad)))
            start = None
    return segments


def cut(y: np.ndarray, sr: int, segments: list[tuple[int, int]]) -> list[np.ndarray]:
    """Each bark on its own: faded at both ends and scaled to BARK_PEAK."""
    fade = int(BARK_FADE_S * sr)
    barks = []
    for a, b in segments:
        bark = y[a:b].astype(np.float32).copy()
        n = min(fade, len(bark) // 2)
        if n:
            ramp = np.linspace(0, 1, n, dtype=np.float32)
            bark[:n] *= ramp
            bark[-n:] *= ramp[::-1]
        peak = np.abs(bark).max()
        if peak > 0:
            bark *= BARK_PEAK / peak
        barks.append(bark)
    return barks


def to_wav(bark: np.ndarray, sr: int) -> bytes:
    """A bark as 16-bit mono WAV bytes."""
    import soundfile

    buf = io.BytesIO()
    soundfile.write(buf, bark, sr, format="WAV", subtype="PCM_16")
    return buf.getvalue()


def write_js(barks: list[bytes], out: Path) -> Path:
    """Write the barks script: a global BARKS, a list of base64 WAVs."""
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "// Generated by `main.py barks` from Adam's bark mark — do not edit.\n"
        "// The original recording: local only, never committed.\n"
        "/* exported BARKS */\n"
    )
    data = [base64.b64encode(b).decode("ascii") for b in barks]
    out.write_text(
        header + "const BARKS = " + json.dumps(data) + "\n", encoding="utf-8"
    )
    return out


def build(clip: Path, out: Path) -> int:
    """Cut the barks out of ``clip`` and pack them into ``out``; how many."""
    import librosa

    if not clip.is_file():
        raise BarkError(
            f"No bark clip at {clip}. Mark the bark in `main.py mark` first "
            "(its clip is cut when the mark is saved)."
        )
    y, sr = librosa.load(clip, sr=None, mono=True)
    barks = cut(y, sr, split(y, sr))
    if not barks:
        raise BarkError(f"No bark found in {clip}: it is silent or too short.")
    write_js([to_wav(b, sr) for b in barks], out)
    return len(barks)
